# Dataset Creation

```{r message=FALSE}
library(knitr)
library(PKPDmisc)
library(tidyverse)
library(vancomycin)
library(mrgsolve)
```

```{r}
source("../scripts/generate_demographics.R")
```
```{r}
models <- source("../models/models.R")$value
```

## Generate data for mrgsolve

start with a baseline of having 100 individuals worth of data, can scale to 
different amounts of individuals later

```{r}
NIDS <- 20
```

```{r}
demogs <- generate_demographics(NIDS) %>% mutate(ID = 1:nrow(.), 
                                                 PMA = PMA/7 # in weeks for stockmann model
                                                 )
```

```{r}
for_dosing <- demogs %>% 
                  mutate(
                      CMT = 1, 
                      EVID = 1,
                      TIME = 0
                  ) %>% select(ID, everything())
```


```{r }
all_dosing <- for_dosing %>% group_by(ID) %>%
    nest() %>%
    mutate(dose = map(data, ~ dosing_6bin_pna_wt(.$AGE, .$WT))
           ) %>% unnest() 
```

Dose for 8 days
```{r}
all_dosing <- all_dosing %>% 
  mutate(addl = 24/II*8) 
```

```{r}
kable(head(all_dosing))
```
```{r}
vanc_stockmann <- models$use("vanc_stockmann")
```

Normalize column capitalizations to make mrgsolve happy

```{r}
mrg_data <- bind_cols(
  all_dosing %>% select(ID),
  all_dosing %>% select(everything(), -ID) %>% lowercase_names()
  ) %>% mutate(amt = dose)
```

```{r}
raw_sim <- vanc_stockmann %>% data_set(mrg_data) %>% mrgsim(end = 10*24) %>%
  as.data.frame %>% as_data_frame %>% capitalize_names()
```
```{r}
raw_sim %>% as.data.frame %>%
  ggplot(aes(x = time, y = CP, group = ID)) +
  geom_line(alpha = 0.6)
  
```


```{r cache = FALSE}
devtools::session_info()
```
